from collections.abc import ItemsView, Iterator, KeysView

class _SortedItemsView[KT, VT](ItemsView[KT, VT]):
    def __reversed__(self) -> Iterator[tuple[KT, VT]]: ...

class SortedDict[KT, VT]:
    def __init__(self) -> None: ...
    def __setitem__(self, key: KT, value: VT) -> None: ...
    def __getitem__(self, key: KT) -> VT: ...
    def __delitem__(self, key: KT) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[KT]: ...
    def items(self) -> _SortedItemsView[KT, VT]: ...
    def keys(self) -> KeysView[KT]: ...
    def setdefault(self, key: KT, default: VT) -> VT: ...
    def peekitem(self, index: int = ...) -> tuple[KT, VT]: ...
